<?php
$users = [
    ["id" => 1,"f_name" => "Tom","l_name" => "Friendly","user_type" => "faculty","status" => "active","client" => "Chrome"],
    ["id" => 2,"f_name" => "Negar","l_name" => "Madani","user_type" => "faculty","status" =>  "inactive","client" => "FireFox"],
    ["id" => 3,"f_name" => "Ashton","l_name" => "Cox","user_type" => "faculty","status" => "active","client" => "FireFox"],
    ["id" => 4,"f_name" => "Cedric","l_name" => "Kelly","user_type" => "student","status" => "inactive","client" => "FireFox"],
    ["id" => 5,"f_name" => "Airi","l_name" => "Satou","user_type" => "faculty","status" => "active","client" => "Chrome"],
    ["id" => 6,"f_name" => "Brielle","l_name" => "Williamson","user_type" => "faculty","status" => "inactive","client" => "Chrome"],
    ["id" => 7,"f_name" => "Herrod","l_name" => "Herrod Chandler","user_type" => "student","status" => "inactive","client" => "Chrome"],
    ["id" => 8,"f_name" => "Rhona","l_name" => "Davidson","user_type" => "faculty","status" => "active","client" => "Chrome"],
    ["id" => 9,"f_name" => "Sam","l_name" => "Kiani","user_type" => "student","status" => "inactive","client" => "Chrome"],
    ["id" => 10,"f_name" => "Sonya","l_name" => "Frost","user_type" => "student","status" => "inactive","client" => "Chrome"],
    ["id" => 11,"f_name" => "Jena","l_name" => "Gaines","user_type" => "faculty","status" => "active","client" => "Chrome"],
    ["id" => 12,"f_name" => "Pari","l_name" => "Naz","user_type" => "faculty","status" => "active","client" => "Chrome"],
    ["id" => 13,"f_name" => "Charde","l_name" => "Marshall","user_type" => "student","status" => "active","client" => "Chrome"],
    ["id" => 14,"f_name" => "Haley","l_name" => "Kennedy","user_type" => "student","status" => "active","client" => "Safari"],
    ["id" => 15,"f_name" => "Tatyana","l_name" => "Fitzpatrick","user_type" => "faculty","status" => "active","client" => "Safari"],
    ["id" => 16,"f_name" => "Michael","l_name" => "Silva","user_type" => "faculty","status" => "active","client" => "Safari"],
    ["id" => 17,"f_name" => "Paul","l_name" => "Byrd","user_type" => "faculty","status" => "active","client" => "Safari"],
    ["id" => 18,"f_name" => "Gloria","l_name" => "Little","user_type" => "student","status" => "active","client" => "Safari"],
    ["id" => 19,"f_name" => "Bradley","l_name" => "Greer","user_type" => "student","status" => "active","client" => "Safari"],
    ["id" => 20,"f_name" => "Dale","l_name" => "Greern","user_type" => "faculty","status" => "active","client" => "Safari"],
    ["id" => 21,"f_name" => "Jenette","l_name" => "Caldwell","user_type" => "student","status" => "active","client" => "IE"],
    ["id" => 22,"f_name" => "Yuri","l_name" => "Berry","user_type" => "student","status" => "active","client" => "IE"],
    ["id" => 23,"f_name" => "Caesar","l_name" => "Vance","user_type" => "student","status" => "active","client" => "IE"],
    ["id" => 24,"f_name" => "Doris","l_name" => "Wilder","user_type" => "student","status" => "active","client" => "IE"]
];