<?php include "header.inc.php";

?>
    <div class = "container">
        <a class="btn btn-primary" href="?page=users" role="button">Back to view record</a>
        <form method="POST">
    <!--Type--> 
 <div class="mb-3">
        <label class="form-label" for="tv">Choose a type of TV:</label>
    <select class="form-control" name="tv" id="tv" required>
      <option value="">Select One</option>
      <option value="LCD">LCD</option>
      <option value="LED">LED</option>
      <option value="OLED">OLED</option>
      <option value="QLED">QLED</option>
    </select>
        </div>
        <!-- Brand -->
<div class="mb-3">
<label class="form-label" for="radio">Please select your brand:</label><br>
        <!-- <p>Please select your brand:</p> -->
      <input type="radio" id="lg" name="lgBrand" value="LG" required="required">
      <label  for="lg">LG</label><br>
      <input  type="radio" id="samsung" name="samsungBrand" value="Samsung" >
      <label  for="samsung">Samsung</label><br>
      <input  type="radio" id="sony" name="sonyBrand" value="Sony" >
      <label  for="sony">Sony</label><br>
        <input  type="radio" id="toshiba" name="toshibaBrand" value="Toshiba" >
      <label  for="toshiba">Toshiba</label><br>
     </div>
    
     <!-- Model -->
    <input type="hidden" name="action" value="create">
        <div class="mb-3">
            <label class="form-label">Model:</label>
            <input type="text" class="form-control" name="modelName" placeholder="Please enter the model">
        </div>
        <!-- Size -->
        <div class="mb-3">
            <label class="form-label">Size:</label>
            <input type="number" class="form-control" name="sizeName" placeholder="Please enter the size">
        </div>
        <!-- Price -->
        <div class="mb-3">
            <label class="form-label">Price:</label>
            <input type="number" step="0.01" class="form-control" name="priceName" placeholder="Please enter the price">
        </div>
        <!-- Description -->
        <div class="mb-3">
            <label class="form-label">Description:</label>
            <input type="text" class="form-control" name="descName" placeholder="Please enter the description">
        </div>
        
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
       



<br>
<?php include "footer.inc.php"; ?>